FILES=Addi.java Call.java Cbrlt.java Computeformaladdress.java Instruction.java Loadi.java Movge.java Movlt.java Or.java Restoreformal.java Storeglobal.java Sub.java Add.java Cbreq.java Cbrne.java Del.java Jumpi.java Loadinargument.java Movgt.java Movne.java Print.java Ret.java Storeinargument.java Xori.java And.java Cbrge.java Compi.java Div.java Loadai.java Loadret.java Mov.java Mult.java Println.java Rsubi.java Storeoutargument.java Bcrgt.java Cbrle.java Comp.java Driver.java Loadglobal.java Moveq.java Movle.java New.java Read.java Storeai.java Storeret.java

all : python Driver.class

Driver.class : ${FILES}
	javac *.java

python : 
	python iloc_cretion.py iloc_template

clean:
	\rm *.class
