FILES=Addi_a.java Call_a.java Cbrlt_a.java Computeformaladdress_a.java Instruction_a.java Loadi_a.java Movge_a.java Movlt_a.java Or_a.java Restoreformal_a.java Storeglobal_a.java Sub_a.java Add_a.java Cbreq_a.java Cbrne_a.java Del_a.java Jumpi_a.java Loadinargument_a.java Movgt_a.java Movne_a.java Print_a.java Ret_a.java Storeinargument_a.java Xori_a.java And_a.java Cbrge_a.java Compi_a.java Div_a.java Loadai_a.java Loadret_a.java Mov_a.java Mult_a.java Println_a.java Rsubi_a.java Storeoutargument_a.java Bcrgt_a.java Cbrle_a.java Comp_a.java Driver_a.java Loadglobal_a.java Moveq_a.java Movle_a.java New_a.java Read_a.java Storeai_a.java Storeret_a.java

all : Driver.class

Driver.class : ${FILES}
	javac *.java

python : 
	#python iloc_cretion.py iloc_template

clean:
	\rm *.class
